backend:
  name: github
  repo: Tchounity/checkgo-documentation
  branch: main
  site_domain: tiny-dolphin-d88b7f.netlify.app
  
media_folder: "docs/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages_principales"
    label: "Pages du site"
    files:
      - name: "index"
        label: "Page d'accueil"
        file: "docs/index.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "lexique"
        label: "Lexique"
        file: "docs/lexique.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "configuration"
    label: "I. Configuration initiale"
    files:
      - name: "connexion-vue-ensemble"
        label: "Connexion et vue d'ensemble"
        file: "docs/configuration/connexion-vue-ensemble.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "utilisateurs"
        label: "Gestion des utilisateurs"
        file: "docs/configuration/utilisateurs.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "modeles-vehicules"
        label: "Modeles de vehicules"
        file: "docs/configuration/modeles-vehicules.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "groupes-vehicules"
        label: "Groupes de vehicules"
        file: "docs/configuration/groupes-vehicules.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "modeles-controles"
        label: "Modeles de controles"
        file: "docs/configuration/modeles-controles.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "ajout-vehicules"
        label: "Ajout de vehicules"
        file: "docs/configuration/ajout-vehicules.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "parametres-techniques"
        label: "Parametres techniques"
        file: "docs/configuration/parametres-techniques.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "flux"
    label: "II. Flux d'utilisation"
    files:
      - name: "creation-contrat"
        label: "Creation d'un contrat"
        file: "docs/flux-utilisation/creation-contrat.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "etat-lieux-depart"
        label: "Etat des lieux de depart"
        file: "docs/flux-utilisation/etat-lieux-depart.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "etat-lieux-retour"
        label: "Etat des lieux de retour"
        file: "docs/flux-utilisation/etat-lieux-retour.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "suivi-rapports"
        label: "Suivi et rapports"
        file: "docs/flux-utilisation/suivi-rapports.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "cas-frequents"
        label: "Cas d'usage frequents"
        file: "docs/flux-utilisation/cas-frequents.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"} 