# Fichier de configuration de test minimal
backend:
  name: github
  repo: Tchounity/checkgo-documentation
  branch: main
  site_domain: tiny-dolphin-d88b7f.netlify.app

media_folder: "docs/assets/images"

collections:
  - name: "test"
    label: "Section de Test"
    folder: "docs/_test"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" } 