backend:
  name: github
  repo: Tchounity/checkgo-documentation
  branch: main
  auth_type: pkce
  app_id: Ov23liEx2R89sDc9vYex

# Dossier media requis pour la validation, meme si on ne l'utilise pas dans ce test.
media_folder: "docs/assets/images"

# Une seule collection de test avec un seul fichier pour isoler le probleme.
collections:
  - name: "test"
    label: "Page de Test"
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "docs/index.md"
        fields:
          - { name: "body", label: "Contenu", widget: "markdown" }

# Collection de test minimale pour valider que le fichier est bien lu.
# Aucun accent n'est utilisé ici.
collections:
  - name: "test_collection"
    label: "Section de Test"
    files:
      - label: "Page d'accueil"
        name: "accueil"
        file: "docs/index.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

media_folder: "docs/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages_principales"
    label: "Pages du site"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "docs/index.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Lexique"
        name: "lexique"
        file: "docs/lexique.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "configuration"
    label: "I. Configuration initiale"
    files:
      - label: "Connexion et vue d'ensemble"
        name: "connexion-vue-ensemble"
        file: "docs/configuration/connexion-vue-ensemble.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Gestion des utilisateurs"
        name: "utilisateurs"
        file: "docs/configuration/utilisateurs.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Modeles de vehicules"
        name: "modeles-vehicules"
        file: "docs/configuration/modeles-vehicules.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Groupes de vehicules"
        name: "groupes-vehicules"
        file: "docs/configuration/groupes-vehicules.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Modeles de controles"
        name: "modeles-controles"
        file: "docs/configuration/modeles-controles.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Ajout de vehicules"
        name: "ajout-vehicules"
        file: "docs/configuration/ajout-vehicules.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Parametres techniques"
        name: "parametres-techniques"
        file: "docs/configuration/parametres-techniques.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "flux"
    label: "II. Flux d'utilisation"
    files:
      - label: "Creation d'un contrat"
        name: "creation-contrat"
        file: "docs/flux-utilisation/creation-contrat.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Etat des lieux de depart"
        name: "etat-lieux-depart"
        file: "docs/flux-utilisation/etat-lieux-depart.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Etat des lieux de retour"
        name: "etat-lieux-retour"
        file: "docs/flux-utilisation/etat-lieux-retour.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Suivi et rapports"
        name: "suivi-rapports"
        file: "docs/flux-utilisation/suivi-rapports.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - label: "Cas d'usage frequents"
        name: "cas-frequents"
        file: "docs/flux-utilisation/cas-frequents.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}